# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Modern AndroidX standards
android.useAndroidX=true
android.nonTransitiveRClass=true

# Suppressing R8's strict rules for compatibility with older ProGuard rules
android.r8.strictFullModeForKeepRules=false